// Copyright 2025 Cisco Systems Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

/*
 * All Webex calling API
 * Webex calling API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetVoicemailSettings200Response
 */
public class GetVoicemailSettings200ResponseTest {
    private final GetVoicemailSettings200Response model = new GetVoicemailSettings200Response();

    /**
     * Model tests for GetVoicemailSettings200Response
     */
    @Test
    public void testGetVoicemailSettings200Response() {
        // TODO: test GetVoicemailSettings200Response
    }

    /**
     * Test the property 'messageExpiryEnabled'
     */
    @Test
    public void messageExpiryEnabledTest() {
        // TODO: test messageExpiryEnabled
    }

    /**
     * Test the property 'numberOfDaysForMessageExpiry'
     */
    @Test
    public void numberOfDaysForMessageExpiryTest() {
        // TODO: test numberOfDaysForMessageExpiry
    }

    /**
     * Test the property 'strictDeletionEnabled'
     */
    @Test
    public void strictDeletionEnabledTest() {
        // TODO: test strictDeletionEnabled
    }

    /**
     * Test the property 'voiceMessageForwardingEnabled'
     */
    @Test
    public void voiceMessageForwardingEnabledTest() {
        // TODO: test voiceMessageForwardingEnabled
    }

}
