// Copyright 2025 Cisco Systems Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

/*
 * All Webex calling API
 * Webex calling API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.client.model.PutLocationVoicemailGroupObjectEmailCopyOfMessage;
import org.openapitools.client.model.PutLocationVoicemailGroupObjectFaxMessage;
import org.openapitools.client.model.PutLocationVoicemailGroupObjectMessageStorage;
import org.openapitools.client.model.PutLocationVoicemailGroupObjectNotifications;
import org.openapitools.client.model.PutLocationVoicemailGroupObjectTransferToNumber;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PutLocationVoicemailGroupObject
 */
public class PutLocationVoicemailGroupObjectTest {
    private final PutLocationVoicemailGroupObject model = new PutLocationVoicemailGroupObject();

    /**
     * Model tests for PutLocationVoicemailGroupObject
     */
    @Test
    public void testPutLocationVoicemailGroupObject() {
        // TODO: test PutLocationVoicemailGroupObject
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'extension'
     */
    @Test
    public void extensionTest() {
        // TODO: test extension
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'passcode'
     */
    @Test
    public void passcodeTest() {
        // TODO: test passcode
    }

    /**
     * Test the property 'languageCode'
     */
    @Test
    public void languageCodeTest() {
        // TODO: test languageCode
    }

    /**
     * Test the property 'greeting'
     */
    @Test
    public void greetingTest() {
        // TODO: test greeting
    }

    /**
     * Test the property 'greetingDescription'
     */
    @Test
    public void greetingDescriptionTest() {
        // TODO: test greetingDescription
    }

    /**
     * Test the property 'messageStorage'
     */
    @Test
    public void messageStorageTest() {
        // TODO: test messageStorage
    }

    /**
     * Test the property 'notifications'
     */
    @Test
    public void notificationsTest() {
        // TODO: test notifications
    }

    /**
     * Test the property 'faxMessage'
     */
    @Test
    public void faxMessageTest() {
        // TODO: test faxMessage
    }

    /**
     * Test the property 'transferToNumber'
     */
    @Test
    public void transferToNumberTest() {
        // TODO: test transferToNumber
    }

    /**
     * Test the property 'emailCopyOfMessage'
     */
    @Test
    public void emailCopyOfMessageTest() {
        // TODO: test emailCopyOfMessage
    }

}
