// Copyright 2025 Cisco Systems Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

/*
 * All Webex calling API
 * Webex calling API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ConfigureVoicemailSettingsForAPersonRequestMessageStorage;
import org.openapitools.client.model.ConfigureVoicemailSettingsForAPersonRequestNotifications;
import org.openapitools.client.model.ConfigureVoicemailSettingsForAPersonRequestSendAllCalls;
import org.openapitools.client.model.ConfigureVoicemailSettingsForAPersonRequestSendBusyCalls;
import org.openapitools.client.model.ConfigureVoicemailSettingsForAPersonRequestSendUnansweredCalls;
import org.openapitools.client.model.ConfigureVoicemailSettingsForAPersonRequestTransferToNumber;
import org.openapitools.client.model.ConfigureVoicemailSettingsForAVirtualLineRequestEmailCopyOfMessage;
import org.openapitools.client.model.ConfigureVoicemailSettingsForAVirtualLineRequestFaxMessage;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ConfigureVoicemailSettingsForAVirtualLineRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-13T15:45:43.258095Z[Europe/Dublin]", comments = "Generator version: 7.9.0")
public class ConfigureVoicemailSettingsForAVirtualLineRequest {
  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  private Boolean enabled;

  public static final String SERIALIZED_NAME_SEND_ALL_CALLS = "sendAllCalls";
  @SerializedName(SERIALIZED_NAME_SEND_ALL_CALLS)
  private ConfigureVoicemailSettingsForAPersonRequestSendAllCalls sendAllCalls;

  public static final String SERIALIZED_NAME_SEND_BUSY_CALLS = "sendBusyCalls";
  @SerializedName(SERIALIZED_NAME_SEND_BUSY_CALLS)
  private ConfigureVoicemailSettingsForAPersonRequestSendBusyCalls sendBusyCalls;

  public static final String SERIALIZED_NAME_SEND_UNANSWERED_CALLS = "sendUnansweredCalls";
  @SerializedName(SERIALIZED_NAME_SEND_UNANSWERED_CALLS)
  private ConfigureVoicemailSettingsForAPersonRequestSendUnansweredCalls sendUnansweredCalls;

  public static final String SERIALIZED_NAME_NOTIFICATIONS = "notifications";
  @SerializedName(SERIALIZED_NAME_NOTIFICATIONS)
  private ConfigureVoicemailSettingsForAPersonRequestNotifications notifications;

  public static final String SERIALIZED_NAME_TRANSFER_TO_NUMBER = "transferToNumber";
  @SerializedName(SERIALIZED_NAME_TRANSFER_TO_NUMBER)
  private ConfigureVoicemailSettingsForAPersonRequestTransferToNumber transferToNumber;

  public static final String SERIALIZED_NAME_EMAIL_COPY_OF_MESSAGE = "emailCopyOfMessage";
  @SerializedName(SERIALIZED_NAME_EMAIL_COPY_OF_MESSAGE)
  private ConfigureVoicemailSettingsForAVirtualLineRequestEmailCopyOfMessage emailCopyOfMessage;

  public static final String SERIALIZED_NAME_MESSAGE_STORAGE = "messageStorage";
  @SerializedName(SERIALIZED_NAME_MESSAGE_STORAGE)
  private ConfigureVoicemailSettingsForAPersonRequestMessageStorage messageStorage;

  public static final String SERIALIZED_NAME_FAX_MESSAGE = "faxMessage";
  @SerializedName(SERIALIZED_NAME_FAX_MESSAGE)
  private ConfigureVoicemailSettingsForAVirtualLineRequestFaxMessage faxMessage;

  public static final String SERIALIZED_NAME_ANNOUNCEMENT_LANGUAGE_CODE = "announcementLanguageCode";
  @SerializedName(SERIALIZED_NAME_ANNOUNCEMENT_LANGUAGE_CODE)
  private String announcementLanguageCode;

  public ConfigureVoicemailSettingsForAVirtualLineRequest() {
  }

  public ConfigureVoicemailSettingsForAVirtualLineRequest enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Voicemail is enabled or disabled.
   * @return enabled
   */
  @javax.annotation.Nullable
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  public ConfigureVoicemailSettingsForAVirtualLineRequest sendAllCalls(ConfigureVoicemailSettingsForAPersonRequestSendAllCalls sendAllCalls) {
    this.sendAllCalls = sendAllCalls;
    return this;
  }

  /**
   * Get sendAllCalls
   * @return sendAllCalls
   */
  @javax.annotation.Nullable
  public ConfigureVoicemailSettingsForAPersonRequestSendAllCalls getSendAllCalls() {
    return sendAllCalls;
  }

  public void setSendAllCalls(ConfigureVoicemailSettingsForAPersonRequestSendAllCalls sendAllCalls) {
    this.sendAllCalls = sendAllCalls;
  }


  public ConfigureVoicemailSettingsForAVirtualLineRequest sendBusyCalls(ConfigureVoicemailSettingsForAPersonRequestSendBusyCalls sendBusyCalls) {
    this.sendBusyCalls = sendBusyCalls;
    return this;
  }

  /**
   * Get sendBusyCalls
   * @return sendBusyCalls
   */
  @javax.annotation.Nullable
  public ConfigureVoicemailSettingsForAPersonRequestSendBusyCalls getSendBusyCalls() {
    return sendBusyCalls;
  }

  public void setSendBusyCalls(ConfigureVoicemailSettingsForAPersonRequestSendBusyCalls sendBusyCalls) {
    this.sendBusyCalls = sendBusyCalls;
  }


  public ConfigureVoicemailSettingsForAVirtualLineRequest sendUnansweredCalls(ConfigureVoicemailSettingsForAPersonRequestSendUnansweredCalls sendUnansweredCalls) {
    this.sendUnansweredCalls = sendUnansweredCalls;
    return this;
  }

  /**
   * Get sendUnansweredCalls
   * @return sendUnansweredCalls
   */
  @javax.annotation.Nullable
  public ConfigureVoicemailSettingsForAPersonRequestSendUnansweredCalls getSendUnansweredCalls() {
    return sendUnansweredCalls;
  }

  public void setSendUnansweredCalls(ConfigureVoicemailSettingsForAPersonRequestSendUnansweredCalls sendUnansweredCalls) {
    this.sendUnansweredCalls = sendUnansweredCalls;
  }


  public ConfigureVoicemailSettingsForAVirtualLineRequest notifications(ConfigureVoicemailSettingsForAPersonRequestNotifications notifications) {
    this.notifications = notifications;
    return this;
  }

  /**
   * Get notifications
   * @return notifications
   */
  @javax.annotation.Nonnull
  public ConfigureVoicemailSettingsForAPersonRequestNotifications getNotifications() {
    return notifications;
  }

  public void setNotifications(ConfigureVoicemailSettingsForAPersonRequestNotifications notifications) {
    this.notifications = notifications;
  }


  public ConfigureVoicemailSettingsForAVirtualLineRequest transferToNumber(ConfigureVoicemailSettingsForAPersonRequestTransferToNumber transferToNumber) {
    this.transferToNumber = transferToNumber;
    return this;
  }

  /**
   * Get transferToNumber
   * @return transferToNumber
   */
  @javax.annotation.Nonnull
  public ConfigureVoicemailSettingsForAPersonRequestTransferToNumber getTransferToNumber() {
    return transferToNumber;
  }

  public void setTransferToNumber(ConfigureVoicemailSettingsForAPersonRequestTransferToNumber transferToNumber) {
    this.transferToNumber = transferToNumber;
  }


  public ConfigureVoicemailSettingsForAVirtualLineRequest emailCopyOfMessage(ConfigureVoicemailSettingsForAVirtualLineRequestEmailCopyOfMessage emailCopyOfMessage) {
    this.emailCopyOfMessage = emailCopyOfMessage;
    return this;
  }

  /**
   * Get emailCopyOfMessage
   * @return emailCopyOfMessage
   */
  @javax.annotation.Nullable
  public ConfigureVoicemailSettingsForAVirtualLineRequestEmailCopyOfMessage getEmailCopyOfMessage() {
    return emailCopyOfMessage;
  }

  public void setEmailCopyOfMessage(ConfigureVoicemailSettingsForAVirtualLineRequestEmailCopyOfMessage emailCopyOfMessage) {
    this.emailCopyOfMessage = emailCopyOfMessage;
  }


  public ConfigureVoicemailSettingsForAVirtualLineRequest messageStorage(ConfigureVoicemailSettingsForAPersonRequestMessageStorage messageStorage) {
    this.messageStorage = messageStorage;
    return this;
  }

  /**
   * Get messageStorage
   * @return messageStorage
   */
  @javax.annotation.Nullable
  public ConfigureVoicemailSettingsForAPersonRequestMessageStorage getMessageStorage() {
    return messageStorage;
  }

  public void setMessageStorage(ConfigureVoicemailSettingsForAPersonRequestMessageStorage messageStorage) {
    this.messageStorage = messageStorage;
  }


  public ConfigureVoicemailSettingsForAVirtualLineRequest faxMessage(ConfigureVoicemailSettingsForAVirtualLineRequestFaxMessage faxMessage) {
    this.faxMessage = faxMessage;
    return this;
  }

  /**
   * Get faxMessage
   * @return faxMessage
   */
  @javax.annotation.Nullable
  public ConfigureVoicemailSettingsForAVirtualLineRequestFaxMessage getFaxMessage() {
    return faxMessage;
  }

  public void setFaxMessage(ConfigureVoicemailSettingsForAVirtualLineRequestFaxMessage faxMessage) {
    this.faxMessage = faxMessage;
  }


  public ConfigureVoicemailSettingsForAVirtualLineRequest announcementLanguageCode(String announcementLanguageCode) {
    this.announcementLanguageCode = announcementLanguageCode;
    return this;
  }

  /**
   * Language code.
   * @return announcementLanguageCode
   */
  @javax.annotation.Nonnull
  public String getAnnouncementLanguageCode() {
    return announcementLanguageCode;
  }

  public void setAnnouncementLanguageCode(String announcementLanguageCode) {
    this.announcementLanguageCode = announcementLanguageCode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigureVoicemailSettingsForAVirtualLineRequest configureVoicemailSettingsForAVirtualLineRequest = (ConfigureVoicemailSettingsForAVirtualLineRequest) o;
    return Objects.equals(this.enabled, configureVoicemailSettingsForAVirtualLineRequest.enabled) &&
        Objects.equals(this.sendAllCalls, configureVoicemailSettingsForAVirtualLineRequest.sendAllCalls) &&
        Objects.equals(this.sendBusyCalls, configureVoicemailSettingsForAVirtualLineRequest.sendBusyCalls) &&
        Objects.equals(this.sendUnansweredCalls, configureVoicemailSettingsForAVirtualLineRequest.sendUnansweredCalls) &&
        Objects.equals(this.notifications, configureVoicemailSettingsForAVirtualLineRequest.notifications) &&
        Objects.equals(this.transferToNumber, configureVoicemailSettingsForAVirtualLineRequest.transferToNumber) &&
        Objects.equals(this.emailCopyOfMessage, configureVoicemailSettingsForAVirtualLineRequest.emailCopyOfMessage) &&
        Objects.equals(this.messageStorage, configureVoicemailSettingsForAVirtualLineRequest.messageStorage) &&
        Objects.equals(this.faxMessage, configureVoicemailSettingsForAVirtualLineRequest.faxMessage) &&
        Objects.equals(this.announcementLanguageCode, configureVoicemailSettingsForAVirtualLineRequest.announcementLanguageCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, sendAllCalls, sendBusyCalls, sendUnansweredCalls, notifications, transferToNumber, emailCopyOfMessage, messageStorage, faxMessage, announcementLanguageCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigureVoicemailSettingsForAVirtualLineRequest {\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    sendAllCalls: ").append(toIndentedString(sendAllCalls)).append("\n");
    sb.append("    sendBusyCalls: ").append(toIndentedString(sendBusyCalls)).append("\n");
    sb.append("    sendUnansweredCalls: ").append(toIndentedString(sendUnansweredCalls)).append("\n");
    sb.append("    notifications: ").append(toIndentedString(notifications)).append("\n");
    sb.append("    transferToNumber: ").append(toIndentedString(transferToNumber)).append("\n");
    sb.append("    emailCopyOfMessage: ").append(toIndentedString(emailCopyOfMessage)).append("\n");
    sb.append("    messageStorage: ").append(toIndentedString(messageStorage)).append("\n");
    sb.append("    faxMessage: ").append(toIndentedString(faxMessage)).append("\n");
    sb.append("    announcementLanguageCode: ").append(toIndentedString(announcementLanguageCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("enabled");
    openapiFields.add("sendAllCalls");
    openapiFields.add("sendBusyCalls");
    openapiFields.add("sendUnansweredCalls");
    openapiFields.add("notifications");
    openapiFields.add("transferToNumber");
    openapiFields.add("emailCopyOfMessage");
    openapiFields.add("messageStorage");
    openapiFields.add("faxMessage");
    openapiFields.add("announcementLanguageCode");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("notifications");
    openapiRequiredFields.add("transferToNumber");
    openapiRequiredFields.add("announcementLanguageCode");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConfigureVoicemailSettingsForAVirtualLineRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConfigureVoicemailSettingsForAVirtualLineRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConfigureVoicemailSettingsForAVirtualLineRequest is not found in the empty JSON string", ConfigureVoicemailSettingsForAVirtualLineRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConfigureVoicemailSettingsForAVirtualLineRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConfigureVoicemailSettingsForAVirtualLineRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ConfigureVoicemailSettingsForAVirtualLineRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `sendAllCalls`
      if (jsonObj.get("sendAllCalls") != null && !jsonObj.get("sendAllCalls").isJsonNull()) {
        ConfigureVoicemailSettingsForAPersonRequestSendAllCalls.validateJsonElement(jsonObj.get("sendAllCalls"));
      }
      // validate the optional field `sendBusyCalls`
      if (jsonObj.get("sendBusyCalls") != null && !jsonObj.get("sendBusyCalls").isJsonNull()) {
        ConfigureVoicemailSettingsForAPersonRequestSendBusyCalls.validateJsonElement(jsonObj.get("sendBusyCalls"));
      }
      // validate the optional field `sendUnansweredCalls`
      if (jsonObj.get("sendUnansweredCalls") != null && !jsonObj.get("sendUnansweredCalls").isJsonNull()) {
        ConfigureVoicemailSettingsForAPersonRequestSendUnansweredCalls.validateJsonElement(jsonObj.get("sendUnansweredCalls"));
      }
      // validate the required field `notifications`
      ConfigureVoicemailSettingsForAPersonRequestNotifications.validateJsonElement(jsonObj.get("notifications"));
      // validate the required field `transferToNumber`
      ConfigureVoicemailSettingsForAPersonRequestTransferToNumber.validateJsonElement(jsonObj.get("transferToNumber"));
      // validate the optional field `emailCopyOfMessage`
      if (jsonObj.get("emailCopyOfMessage") != null && !jsonObj.get("emailCopyOfMessage").isJsonNull()) {
        ConfigureVoicemailSettingsForAVirtualLineRequestEmailCopyOfMessage.validateJsonElement(jsonObj.get("emailCopyOfMessage"));
      }
      // validate the optional field `messageStorage`
      if (jsonObj.get("messageStorage") != null && !jsonObj.get("messageStorage").isJsonNull()) {
        ConfigureVoicemailSettingsForAPersonRequestMessageStorage.validateJsonElement(jsonObj.get("messageStorage"));
      }
      // validate the optional field `faxMessage`
      if (jsonObj.get("faxMessage") != null && !jsonObj.get("faxMessage").isJsonNull()) {
        ConfigureVoicemailSettingsForAVirtualLineRequestFaxMessage.validateJsonElement(jsonObj.get("faxMessage"));
      }
      if (!jsonObj.get("announcementLanguageCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `announcementLanguageCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("announcementLanguageCode").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConfigureVoicemailSettingsForAVirtualLineRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConfigureVoicemailSettingsForAVirtualLineRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConfigureVoicemailSettingsForAVirtualLineRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConfigureVoicemailSettingsForAVirtualLineRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ConfigureVoicemailSettingsForAVirtualLineRequest>() {
           @Override
           public void write(JsonWriter out, ConfigureVoicemailSettingsForAVirtualLineRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConfigureVoicemailSettingsForAVirtualLineRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConfigureVoicemailSettingsForAVirtualLineRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConfigureVoicemailSettingsForAVirtualLineRequest
   * @throws IOException if the JSON string is invalid with respect to ConfigureVoicemailSettingsForAVirtualLineRequest
   */
  public static ConfigureVoicemailSettingsForAVirtualLineRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConfigureVoicemailSettingsForAVirtualLineRequest.class);
  }

  /**
   * Convert an instance of ConfigureVoicemailSettingsForAVirtualLineRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

