// Copyright 2025 Cisco Systems Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

/*
 * All Webex calling API
 * Webex calling API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.CreateAWorkspace201ResponseCallingHybridCalling;
import org.openapitools.client.model.CreateAWorkspace201ResponseCallingWebexCalling;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Calling type.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-13T15:45:43.258095Z[Europe/Dublin]", comments = "Generator version: 7.9.0")
public class CreateAWorkspace201ResponseCalling {
  /**
   * Calling.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    FREE_CALLING("freeCalling"),
    
    HYBRID_CALLING("hybridCalling"),
    
    WEBEX_CALLING("webexCalling"),
    
    WEBEX_EDGE_FOR_DEVICES("webexEdgeForDevices"),
    
    THIRD_PARTY_SIP_CALLING("thirdPartySipCalling"),
    
    NONE("none");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;

  public static final String SERIALIZED_NAME_HYBRID_CALLING = "hybridCalling";
  @SerializedName(SERIALIZED_NAME_HYBRID_CALLING)
  private CreateAWorkspace201ResponseCallingHybridCalling hybridCalling;

  public static final String SERIALIZED_NAME_WEBEX_CALLING = "webexCalling";
  @SerializedName(SERIALIZED_NAME_WEBEX_CALLING)
  private CreateAWorkspace201ResponseCallingWebexCalling webexCalling;

  public CreateAWorkspace201ResponseCalling() {
  }

  public CreateAWorkspace201ResponseCalling type(TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Calling.
   * @return type
   */
  @javax.annotation.Nullable
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  public CreateAWorkspace201ResponseCalling hybridCalling(CreateAWorkspace201ResponseCallingHybridCalling hybridCalling) {
    this.hybridCalling = hybridCalling;
    return this;
  }

  /**
   * Get hybridCalling
   * @return hybridCalling
   */
  @javax.annotation.Nullable
  public CreateAWorkspace201ResponseCallingHybridCalling getHybridCalling() {
    return hybridCalling;
  }

  public void setHybridCalling(CreateAWorkspace201ResponseCallingHybridCalling hybridCalling) {
    this.hybridCalling = hybridCalling;
  }


  public CreateAWorkspace201ResponseCalling webexCalling(CreateAWorkspace201ResponseCallingWebexCalling webexCalling) {
    this.webexCalling = webexCalling;
    return this;
  }

  /**
   * Get webexCalling
   * @return webexCalling
   */
  @javax.annotation.Nullable
  public CreateAWorkspace201ResponseCallingWebexCalling getWebexCalling() {
    return webexCalling;
  }

  public void setWebexCalling(CreateAWorkspace201ResponseCallingWebexCalling webexCalling) {
    this.webexCalling = webexCalling;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateAWorkspace201ResponseCalling createAWorkspace201ResponseCalling = (CreateAWorkspace201ResponseCalling) o;
    return Objects.equals(this.type, createAWorkspace201ResponseCalling.type) &&
        Objects.equals(this.hybridCalling, createAWorkspace201ResponseCalling.hybridCalling) &&
        Objects.equals(this.webexCalling, createAWorkspace201ResponseCalling.webexCalling);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, hybridCalling, webexCalling);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateAWorkspace201ResponseCalling {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    hybridCalling: ").append(toIndentedString(hybridCalling)).append("\n");
    sb.append("    webexCalling: ").append(toIndentedString(webexCalling)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("type");
    openapiFields.add("hybridCalling");
    openapiFields.add("webexCalling");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateAWorkspace201ResponseCalling
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateAWorkspace201ResponseCalling.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateAWorkspace201ResponseCalling is not found in the empty JSON string", CreateAWorkspace201ResponseCalling.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateAWorkspace201ResponseCalling.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateAWorkspace201ResponseCalling` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // validate the optional field `type`
      if (jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) {
        TypeEnum.validateJsonElement(jsonObj.get("type"));
      }
      // validate the optional field `hybridCalling`
      if (jsonObj.get("hybridCalling") != null && !jsonObj.get("hybridCalling").isJsonNull()) {
        CreateAWorkspace201ResponseCallingHybridCalling.validateJsonElement(jsonObj.get("hybridCalling"));
      }
      // validate the optional field `webexCalling`
      if (jsonObj.get("webexCalling") != null && !jsonObj.get("webexCalling").isJsonNull()) {
        CreateAWorkspace201ResponseCallingWebexCalling.validateJsonElement(jsonObj.get("webexCalling"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateAWorkspace201ResponseCalling.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateAWorkspace201ResponseCalling' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateAWorkspace201ResponseCalling> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateAWorkspace201ResponseCalling.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateAWorkspace201ResponseCalling>() {
           @Override
           public void write(JsonWriter out, CreateAWorkspace201ResponseCalling value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateAWorkspace201ResponseCalling read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateAWorkspace201ResponseCalling given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateAWorkspace201ResponseCalling
   * @throws IOException if the JSON string is invalid with respect to CreateAWorkspace201ResponseCalling
   */
  public static CreateAWorkspace201ResponseCalling fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateAWorkspace201ResponseCalling.class);
  }

  /**
   * Convert an instance of CreateAWorkspace201ResponseCalling to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

