// Copyright 2025 Cisco Systems Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

/*
 * All Webex calling API
 * Webex calling API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Specifies the event recur weekly on the designated days of the week. Not allowed with &#x60;recurDaily&#x60;.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-13T15:45:43.258095Z[Europe/Dublin]", comments = "Generator version: 7.9.0")
public class EventLongDetailsRecurrenceRecurWeekly {
  public static final String SERIALIZED_NAME_RECUR_INTERVAL = "recurInterval";
  @SerializedName(SERIALIZED_NAME_RECUR_INTERVAL)
  private BigDecimal recurInterval;

  public static final String SERIALIZED_NAME_SUNDAY = "sunday";
  @SerializedName(SERIALIZED_NAME_SUNDAY)
  private Boolean sunday;

  public static final String SERIALIZED_NAME_MONDAY = "monday";
  @SerializedName(SERIALIZED_NAME_MONDAY)
  private Boolean monday;

  public static final String SERIALIZED_NAME_TUESDAY = "tuesday";
  @SerializedName(SERIALIZED_NAME_TUESDAY)
  private Boolean tuesday;

  public static final String SERIALIZED_NAME_WEDNESDAY = "wednesday";
  @SerializedName(SERIALIZED_NAME_WEDNESDAY)
  private Boolean wednesday;

  public static final String SERIALIZED_NAME_THURSDAY = "thursday";
  @SerializedName(SERIALIZED_NAME_THURSDAY)
  private Boolean thursday;

  public static final String SERIALIZED_NAME_FRIDAY = "friday";
  @SerializedName(SERIALIZED_NAME_FRIDAY)
  private Boolean friday;

  public static final String SERIALIZED_NAME_SATURDAY = "saturday";
  @SerializedName(SERIALIZED_NAME_SATURDAY)
  private Boolean saturday;

  public EventLongDetailsRecurrenceRecurWeekly() {
  }

  public EventLongDetailsRecurrenceRecurWeekly recurInterval(BigDecimal recurInterval) {
    this.recurInterval = recurInterval;
    return this;
  }

  /**
   * Specifies the number of weeks between the start of each recurrence.
   * @return recurInterval
   */
  @javax.annotation.Nonnull
  public BigDecimal getRecurInterval() {
    return recurInterval;
  }

  public void setRecurInterval(BigDecimal recurInterval) {
    this.recurInterval = recurInterval;
  }


  public EventLongDetailsRecurrenceRecurWeekly sunday(Boolean sunday) {
    this.sunday = sunday;
    return this;
  }

  /**
   * Indicates event occurs weekly on Sunday.
   * @return sunday
   */
  @javax.annotation.Nullable
  public Boolean getSunday() {
    return sunday;
  }

  public void setSunday(Boolean sunday) {
    this.sunday = sunday;
  }


  public EventLongDetailsRecurrenceRecurWeekly monday(Boolean monday) {
    this.monday = monday;
    return this;
  }

  /**
   * Indicates event occurs weekly on Monday.
   * @return monday
   */
  @javax.annotation.Nullable
  public Boolean getMonday() {
    return monday;
  }

  public void setMonday(Boolean monday) {
    this.monday = monday;
  }


  public EventLongDetailsRecurrenceRecurWeekly tuesday(Boolean tuesday) {
    this.tuesday = tuesday;
    return this;
  }

  /**
   * Indicates event occurs weekly on Tuesday.
   * @return tuesday
   */
  @javax.annotation.Nullable
  public Boolean getTuesday() {
    return tuesday;
  }

  public void setTuesday(Boolean tuesday) {
    this.tuesday = tuesday;
  }


  public EventLongDetailsRecurrenceRecurWeekly wednesday(Boolean wednesday) {
    this.wednesday = wednesday;
    return this;
  }

  /**
   * Indicates event occurs weekly on Wednesday.
   * @return wednesday
   */
  @javax.annotation.Nullable
  public Boolean getWednesday() {
    return wednesday;
  }

  public void setWednesday(Boolean wednesday) {
    this.wednesday = wednesday;
  }


  public EventLongDetailsRecurrenceRecurWeekly thursday(Boolean thursday) {
    this.thursday = thursday;
    return this;
  }

  /**
   * Indicates event occurs weekly on Thursday.
   * @return thursday
   */
  @javax.annotation.Nullable
  public Boolean getThursday() {
    return thursday;
  }

  public void setThursday(Boolean thursday) {
    this.thursday = thursday;
  }


  public EventLongDetailsRecurrenceRecurWeekly friday(Boolean friday) {
    this.friday = friday;
    return this;
  }

  /**
   * Indicates event occurs weekly on Friday.
   * @return friday
   */
  @javax.annotation.Nullable
  public Boolean getFriday() {
    return friday;
  }

  public void setFriday(Boolean friday) {
    this.friday = friday;
  }


  public EventLongDetailsRecurrenceRecurWeekly saturday(Boolean saturday) {
    this.saturday = saturday;
    return this;
  }

  /**
   * Indicates event occurs weekly on Saturday.
   * @return saturday
   */
  @javax.annotation.Nullable
  public Boolean getSaturday() {
    return saturday;
  }

  public void setSaturday(Boolean saturday) {
    this.saturday = saturday;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventLongDetailsRecurrenceRecurWeekly eventLongDetailsRecurrenceRecurWeekly = (EventLongDetailsRecurrenceRecurWeekly) o;
    return Objects.equals(this.recurInterval, eventLongDetailsRecurrenceRecurWeekly.recurInterval) &&
        Objects.equals(this.sunday, eventLongDetailsRecurrenceRecurWeekly.sunday) &&
        Objects.equals(this.monday, eventLongDetailsRecurrenceRecurWeekly.monday) &&
        Objects.equals(this.tuesday, eventLongDetailsRecurrenceRecurWeekly.tuesday) &&
        Objects.equals(this.wednesday, eventLongDetailsRecurrenceRecurWeekly.wednesday) &&
        Objects.equals(this.thursday, eventLongDetailsRecurrenceRecurWeekly.thursday) &&
        Objects.equals(this.friday, eventLongDetailsRecurrenceRecurWeekly.friday) &&
        Objects.equals(this.saturday, eventLongDetailsRecurrenceRecurWeekly.saturday);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recurInterval, sunday, monday, tuesday, wednesday, thursday, friday, saturday);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventLongDetailsRecurrenceRecurWeekly {\n");
    sb.append("    recurInterval: ").append(toIndentedString(recurInterval)).append("\n");
    sb.append("    sunday: ").append(toIndentedString(sunday)).append("\n");
    sb.append("    monday: ").append(toIndentedString(monday)).append("\n");
    sb.append("    tuesday: ").append(toIndentedString(tuesday)).append("\n");
    sb.append("    wednesday: ").append(toIndentedString(wednesday)).append("\n");
    sb.append("    thursday: ").append(toIndentedString(thursday)).append("\n");
    sb.append("    friday: ").append(toIndentedString(friday)).append("\n");
    sb.append("    saturday: ").append(toIndentedString(saturday)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("recurInterval");
    openapiFields.add("sunday");
    openapiFields.add("monday");
    openapiFields.add("tuesday");
    openapiFields.add("wednesday");
    openapiFields.add("thursday");
    openapiFields.add("friday");
    openapiFields.add("saturday");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("recurInterval");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EventLongDetailsRecurrenceRecurWeekly
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EventLongDetailsRecurrenceRecurWeekly.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EventLongDetailsRecurrenceRecurWeekly is not found in the empty JSON string", EventLongDetailsRecurrenceRecurWeekly.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EventLongDetailsRecurrenceRecurWeekly.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EventLongDetailsRecurrenceRecurWeekly` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EventLongDetailsRecurrenceRecurWeekly.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EventLongDetailsRecurrenceRecurWeekly.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EventLongDetailsRecurrenceRecurWeekly' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EventLongDetailsRecurrenceRecurWeekly> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EventLongDetailsRecurrenceRecurWeekly.class));

       return (TypeAdapter<T>) new TypeAdapter<EventLongDetailsRecurrenceRecurWeekly>() {
           @Override
           public void write(JsonWriter out, EventLongDetailsRecurrenceRecurWeekly value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EventLongDetailsRecurrenceRecurWeekly read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EventLongDetailsRecurrenceRecurWeekly given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EventLongDetailsRecurrenceRecurWeekly
   * @throws IOException if the JSON string is invalid with respect to EventLongDetailsRecurrenceRecurWeekly
   */
  public static EventLongDetailsRecurrenceRecurWeekly fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EventLongDetailsRecurrenceRecurWeekly.class);
  }

  /**
   * Convert an instance of EventLongDetailsRecurrenceRecurWeekly to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

