// Copyright 2025 Cisco Systems Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

/*
 * All Webex calling API
 * Webex calling API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-13T15:45:43.258095Z[Europe/Dublin]", comments = "Generator version: 7.9.0")
public class GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response {
  public static final String SERIALIZED_NAME_INBOUND_P_S_T_N_CALLS_ENABLED = "inboundPSTNCallsEnabled";
  @SerializedName(SERIALIZED_NAME_INBOUND_P_S_T_N_CALLS_ENABLED)
  private Boolean inboundPSTNCallsEnabled;

  public static final String SERIALIZED_NAME_OUTBOUND_P_S_T_N_CALLS_ENABLED = "outboundPSTNCallsEnabled";
  @SerializedName(SERIALIZED_NAME_OUTBOUND_P_S_T_N_CALLS_ENABLED)
  private Boolean outboundPSTNCallsEnabled;

  public static final String SERIALIZED_NAME_OUTBOUND_P_S_T_N_CALLS_DELAY_ENABLED = "outboundPSTNCallsDelayEnabled";
  @SerializedName(SERIALIZED_NAME_OUTBOUND_P_S_T_N_CALLS_DELAY_ENABLED)
  private Boolean outboundPSTNCallsDelayEnabled;

  public static final String SERIALIZED_NAME_DELAY_IN_SECONDS = "delayInSeconds";
  @SerializedName(SERIALIZED_NAME_DELAY_IN_SECONDS)
  private BigDecimal delayInSeconds;

  public GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response() {
  }

  public GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response inboundPSTNCallsEnabled(Boolean inboundPSTNCallsEnabled) {
    this.inboundPSTNCallsEnabled = inboundPSTNCallsEnabled;
    return this;
  }

  /**
   * Flag to indicate whether the Call Recording START/STOP announcement is played to an inbound caller.
   * @return inboundPSTNCallsEnabled
   */
  @javax.annotation.Nonnull
  public Boolean getInboundPSTNCallsEnabled() {
    return inboundPSTNCallsEnabled;
  }

  public void setInboundPSTNCallsEnabled(Boolean inboundPSTNCallsEnabled) {
    this.inboundPSTNCallsEnabled = inboundPSTNCallsEnabled;
  }


  public GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response outboundPSTNCallsEnabled(Boolean outboundPSTNCallsEnabled) {
    this.outboundPSTNCallsEnabled = outboundPSTNCallsEnabled;
    return this;
  }

  /**
   * Flag to indicate whether the Call Recording START/STOP announcement is played to an outbound caller.
   * @return outboundPSTNCallsEnabled
   */
  @javax.annotation.Nonnull
  public Boolean getOutboundPSTNCallsEnabled() {
    return outboundPSTNCallsEnabled;
  }

  public void setOutboundPSTNCallsEnabled(Boolean outboundPSTNCallsEnabled) {
    this.outboundPSTNCallsEnabled = outboundPSTNCallsEnabled;
  }


  public GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response outboundPSTNCallsDelayEnabled(Boolean outboundPSTNCallsDelayEnabled) {
    this.outboundPSTNCallsDelayEnabled = outboundPSTNCallsDelayEnabled;
    return this;
  }

  /**
   * Flag to indicate whether compliance announcement is played after a specified delay in seconds.
   * @return outboundPSTNCallsDelayEnabled
   */
  @javax.annotation.Nonnull
  public Boolean getOutboundPSTNCallsDelayEnabled() {
    return outboundPSTNCallsDelayEnabled;
  }

  public void setOutboundPSTNCallsDelayEnabled(Boolean outboundPSTNCallsDelayEnabled) {
    this.outboundPSTNCallsDelayEnabled = outboundPSTNCallsDelayEnabled;
  }


  public GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response delayInSeconds(BigDecimal delayInSeconds) {
    this.delayInSeconds = delayInSeconds;
    return this;
  }

  /**
   * Number of seconds to wait before playing the compliance announcement.
   * @return delayInSeconds
   */
  @javax.annotation.Nonnull
  public BigDecimal getDelayInSeconds() {
    return delayInSeconds;
  }

  public void setDelayInSeconds(BigDecimal delayInSeconds) {
    this.delayInSeconds = delayInSeconds;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response getDetailsForTheOrganizationComplianceAnnouncementSetting200Response = (GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response) o;
    return Objects.equals(this.inboundPSTNCallsEnabled, getDetailsForTheOrganizationComplianceAnnouncementSetting200Response.inboundPSTNCallsEnabled) &&
        Objects.equals(this.outboundPSTNCallsEnabled, getDetailsForTheOrganizationComplianceAnnouncementSetting200Response.outboundPSTNCallsEnabled) &&
        Objects.equals(this.outboundPSTNCallsDelayEnabled, getDetailsForTheOrganizationComplianceAnnouncementSetting200Response.outboundPSTNCallsDelayEnabled) &&
        Objects.equals(this.delayInSeconds, getDetailsForTheOrganizationComplianceAnnouncementSetting200Response.delayInSeconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inboundPSTNCallsEnabled, outboundPSTNCallsEnabled, outboundPSTNCallsDelayEnabled, delayInSeconds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response {\n");
    sb.append("    inboundPSTNCallsEnabled: ").append(toIndentedString(inboundPSTNCallsEnabled)).append("\n");
    sb.append("    outboundPSTNCallsEnabled: ").append(toIndentedString(outboundPSTNCallsEnabled)).append("\n");
    sb.append("    outboundPSTNCallsDelayEnabled: ").append(toIndentedString(outboundPSTNCallsDelayEnabled)).append("\n");
    sb.append("    delayInSeconds: ").append(toIndentedString(delayInSeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("inboundPSTNCallsEnabled");
    openapiFields.add("outboundPSTNCallsEnabled");
    openapiFields.add("outboundPSTNCallsDelayEnabled");
    openapiFields.add("delayInSeconds");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("inboundPSTNCallsEnabled");
    openapiRequiredFields.add("outboundPSTNCallsEnabled");
    openapiRequiredFields.add("outboundPSTNCallsDelayEnabled");
    openapiRequiredFields.add("delayInSeconds");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response is not found in the empty JSON string", GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response>() {
           @Override
           public void write(JsonWriter out, GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response
   * @throws IOException if the JSON string is invalid with respect to GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response
   */
  public static GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response.class);
  }

  /**
   * Convert an instance of GetDetailsForTheOrganizationComplianceAnnouncementSetting200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

