// Copyright 2025 Cisco Systems Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

/*
 * All Webex calling API
 * Webex calling API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ECBNSelectionType;
import org.openapitools.client.model.GetPersonCallbackNumberObjectDirectLineInfo;
import org.openapitools.client.model.GetPersonCallbackNumberObjectLocationECBNInfo;
import org.openapitools.client.model.GetPersonCallbackNumberObjectLocationMemberInfo;
import org.openapitools.client.model.GetWorkspaceCallbackNumberObjectDefaultInfo;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GetPersonCallbackNumberObject
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-13T15:45:43.258095Z[Europe/Dublin]", comments = "Generator version: 7.9.0")
public class GetPersonCallbackNumberObject {
  public static final String SERIALIZED_NAME_SELECTED = "selected";
  @SerializedName(SERIALIZED_NAME_SELECTED)
  private ECBNSelectionType selected;

  public static final String SERIALIZED_NAME_DIRECT_LINE_INFO = "directLineInfo";
  @SerializedName(SERIALIZED_NAME_DIRECT_LINE_INFO)
  private GetPersonCallbackNumberObjectDirectLineInfo directLineInfo;

  public static final String SERIALIZED_NAME_LOCATION_E_C_B_N_INFO = "locationECBNInfo";
  @SerializedName(SERIALIZED_NAME_LOCATION_E_C_B_N_INFO)
  private GetPersonCallbackNumberObjectLocationECBNInfo locationECBNInfo;

  public static final String SERIALIZED_NAME_LOCATION_MEMBER_INFO = "locationMemberInfo";
  @SerializedName(SERIALIZED_NAME_LOCATION_MEMBER_INFO)
  private GetPersonCallbackNumberObjectLocationMemberInfo locationMemberInfo;

  public static final String SERIALIZED_NAME_DEFAULT_INFO = "defaultInfo";
  @SerializedName(SERIALIZED_NAME_DEFAULT_INFO)
  private GetWorkspaceCallbackNumberObjectDefaultInfo defaultInfo;

  public GetPersonCallbackNumberObject() {
  }

  public GetPersonCallbackNumberObject selected(ECBNSelectionType selected) {
    this.selected = selected;
    return this;
  }

  /**
   * Selected number type to configure emergency callback.
   * @return selected
   */
  @javax.annotation.Nullable
  public ECBNSelectionType getSelected() {
    return selected;
  }

  public void setSelected(ECBNSelectionType selected) {
    this.selected = selected;
  }


  public GetPersonCallbackNumberObject directLineInfo(GetPersonCallbackNumberObjectDirectLineInfo directLineInfo) {
    this.directLineInfo = directLineInfo;
    return this;
  }

  /**
   * Get directLineInfo
   * @return directLineInfo
   */
  @javax.annotation.Nullable
  public GetPersonCallbackNumberObjectDirectLineInfo getDirectLineInfo() {
    return directLineInfo;
  }

  public void setDirectLineInfo(GetPersonCallbackNumberObjectDirectLineInfo directLineInfo) {
    this.directLineInfo = directLineInfo;
  }


  public GetPersonCallbackNumberObject locationECBNInfo(GetPersonCallbackNumberObjectLocationECBNInfo locationECBNInfo) {
    this.locationECBNInfo = locationECBNInfo;
    return this;
  }

  /**
   * Get locationECBNInfo
   * @return locationECBNInfo
   */
  @javax.annotation.Nullable
  public GetPersonCallbackNumberObjectLocationECBNInfo getLocationECBNInfo() {
    return locationECBNInfo;
  }

  public void setLocationECBNInfo(GetPersonCallbackNumberObjectLocationECBNInfo locationECBNInfo) {
    this.locationECBNInfo = locationECBNInfo;
  }


  public GetPersonCallbackNumberObject locationMemberInfo(GetPersonCallbackNumberObjectLocationMemberInfo locationMemberInfo) {
    this.locationMemberInfo = locationMemberInfo;
    return this;
  }

  /**
   * Get locationMemberInfo
   * @return locationMemberInfo
   */
  @javax.annotation.Nullable
  public GetPersonCallbackNumberObjectLocationMemberInfo getLocationMemberInfo() {
    return locationMemberInfo;
  }

  public void setLocationMemberInfo(GetPersonCallbackNumberObjectLocationMemberInfo locationMemberInfo) {
    this.locationMemberInfo = locationMemberInfo;
  }


  public GetPersonCallbackNumberObject defaultInfo(GetWorkspaceCallbackNumberObjectDefaultInfo defaultInfo) {
    this.defaultInfo = defaultInfo;
    return this;
  }

  /**
   * Get defaultInfo
   * @return defaultInfo
   */
  @javax.annotation.Nullable
  public GetWorkspaceCallbackNumberObjectDefaultInfo getDefaultInfo() {
    return defaultInfo;
  }

  public void setDefaultInfo(GetWorkspaceCallbackNumberObjectDefaultInfo defaultInfo) {
    this.defaultInfo = defaultInfo;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPersonCallbackNumberObject getPersonCallbackNumberObject = (GetPersonCallbackNumberObject) o;
    return Objects.equals(this.selected, getPersonCallbackNumberObject.selected) &&
        Objects.equals(this.directLineInfo, getPersonCallbackNumberObject.directLineInfo) &&
        Objects.equals(this.locationECBNInfo, getPersonCallbackNumberObject.locationECBNInfo) &&
        Objects.equals(this.locationMemberInfo, getPersonCallbackNumberObject.locationMemberInfo) &&
        Objects.equals(this.defaultInfo, getPersonCallbackNumberObject.defaultInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(selected, directLineInfo, locationECBNInfo, locationMemberInfo, defaultInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPersonCallbackNumberObject {\n");
    sb.append("    selected: ").append(toIndentedString(selected)).append("\n");
    sb.append("    directLineInfo: ").append(toIndentedString(directLineInfo)).append("\n");
    sb.append("    locationECBNInfo: ").append(toIndentedString(locationECBNInfo)).append("\n");
    sb.append("    locationMemberInfo: ").append(toIndentedString(locationMemberInfo)).append("\n");
    sb.append("    defaultInfo: ").append(toIndentedString(defaultInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("selected");
    openapiFields.add("directLineInfo");
    openapiFields.add("locationECBNInfo");
    openapiFields.add("locationMemberInfo");
    openapiFields.add("defaultInfo");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetPersonCallbackNumberObject
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetPersonCallbackNumberObject.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetPersonCallbackNumberObject is not found in the empty JSON string", GetPersonCallbackNumberObject.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetPersonCallbackNumberObject.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetPersonCallbackNumberObject` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `selected`
      if (jsonObj.get("selected") != null && !jsonObj.get("selected").isJsonNull()) {
        ECBNSelectionType.validateJsonElement(jsonObj.get("selected"));
      }
      // validate the optional field `directLineInfo`
      if (jsonObj.get("directLineInfo") != null && !jsonObj.get("directLineInfo").isJsonNull()) {
        GetPersonCallbackNumberObjectDirectLineInfo.validateJsonElement(jsonObj.get("directLineInfo"));
      }
      // validate the optional field `locationECBNInfo`
      if (jsonObj.get("locationECBNInfo") != null && !jsonObj.get("locationECBNInfo").isJsonNull()) {
        GetPersonCallbackNumberObjectLocationECBNInfo.validateJsonElement(jsonObj.get("locationECBNInfo"));
      }
      // validate the optional field `locationMemberInfo`
      if (jsonObj.get("locationMemberInfo") != null && !jsonObj.get("locationMemberInfo").isJsonNull()) {
        GetPersonCallbackNumberObjectLocationMemberInfo.validateJsonElement(jsonObj.get("locationMemberInfo"));
      }
      // validate the optional field `defaultInfo`
      if (jsonObj.get("defaultInfo") != null && !jsonObj.get("defaultInfo").isJsonNull()) {
        GetWorkspaceCallbackNumberObjectDefaultInfo.validateJsonElement(jsonObj.get("defaultInfo"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetPersonCallbackNumberObject.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetPersonCallbackNumberObject' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetPersonCallbackNumberObject> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetPersonCallbackNumberObject.class));

       return (TypeAdapter<T>) new TypeAdapter<GetPersonCallbackNumberObject>() {
           @Override
           public void write(JsonWriter out, GetPersonCallbackNumberObject value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetPersonCallbackNumberObject read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetPersonCallbackNumberObject given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetPersonCallbackNumberObject
   * @throws IOException if the JSON string is invalid with respect to GetPersonCallbackNumberObject
   */
  public static GetPersonCallbackNumberObject fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetPersonCallbackNumberObject.class);
  }

  /**
   * Convert an instance of GetPersonCallbackNumberObject to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

