// Copyright 2025 Cisco Systems Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

/*
 * All Webex calling API
 * Webex calling API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Location of the DECT network.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-13T15:45:43.258095Z[Europe/Dublin]", comments = "Generator version: 7.9.0")
public class GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation() {
  }

  public GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Location identifier associated with the member.
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Location name associated with the member.
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation getTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation = (GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation) o;
    return Objects.equals(this.id, getTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation.id) &&
        Objects.equals(this.name, getTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("name");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("name");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation is not found in the empty JSON string", GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation.class));

       return (TypeAdapter<T>) new TypeAdapter<GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation>() {
           @Override
           public void write(JsonWriter out, GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation
   * @throws IOException if the JSON string is invalid with respect to GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation
   */
  public static GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation.class);
  }

  /**
   * Convert an instance of GetTheListOfDECTNetworksForAnOrganization200ResponseDectNetworksInnerLocation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

