// Copyright 2025 Cisco Systems Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

/*
 * All Webex calling API
 * Webex calling API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Location;
import org.openapitools.client.model.MemberType;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Lines
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-13T15:45:43.258095Z[Europe/Dublin]", comments = "Generator version: 7.9.0")
public class Lines {
  public static final String SERIALIZED_NAME_MEMBER_ID = "memberId";
  @SerializedName(SERIALIZED_NAME_MEMBER_ID)
  private String memberId;

  public static final String SERIALIZED_NAME_FIRST_NAME = "firstName";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  private String firstName;

  public static final String SERIALIZED_NAME_LAST_NAME = "lastName";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  private String lastName;

  public static final String SERIALIZED_NAME_EXTERNAL = "external";
  @SerializedName(SERIALIZED_NAME_EXTERNAL)
  private String external;

  public static final String SERIALIZED_NAME_EXTENSION = "extension";
  @SerializedName(SERIALIZED_NAME_EXTENSION)
  private String extension;

  public static final String SERIALIZED_NAME_LAST_REGISTRATION_TIME = "lastRegistrationTime";
  @SerializedName(SERIALIZED_NAME_LAST_REGISTRATION_TIME)
  private String lastRegistrationTime;

  public static final String SERIALIZED_NAME_HOST_I_P = "hostIP";
  @SerializedName(SERIALIZED_NAME_HOST_I_P)
  private String hostIP;

  public static final String SERIALIZED_NAME_REMOTE_I_P = "remoteIP";
  @SerializedName(SERIALIZED_NAME_REMOTE_I_P)
  private String remoteIP;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private Location location;

  public static final String SERIALIZED_NAME_MEMBER_TYPE = "memberType";
  @SerializedName(SERIALIZED_NAME_MEMBER_TYPE)
  private MemberType memberType;

  public Lines() {
  }

  public Lines memberId(String memberId) {
    this.memberId = memberId;
    return this;
  }

  /**
   * ID of the member on line1 of the handset. Members can be PEOPLE or PLACE.
   * @return memberId
   */
  @javax.annotation.Nonnull
  public String getMemberId() {
    return memberId;
  }

  public void setMemberId(String memberId) {
    this.memberId = memberId;
  }


  public Lines firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * Line members&#39;s first name.
   * @return firstName
   */
  @javax.annotation.Nonnull
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public Lines lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

  /**
   * Line members&#39;s last name.
   * @return lastName
   */
  @javax.annotation.Nonnull
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public Lines external(String external) {
    this.external = external;
    return this;
  }

  /**
   * Line members primary number.
   * @return external
   */
  @javax.annotation.Nullable
  public String getExternal() {
    return external;
  }

  public void setExternal(String external) {
    this.external = external;
  }


  public Lines extension(String extension) {
    this.extension = extension;
    return this;
  }

  /**
   * Line members extension.
   * @return extension
   */
  @javax.annotation.Nullable
  public String getExtension() {
    return extension;
  }

  public void setExtension(String extension) {
    this.extension = extension;
  }


  public Lines lastRegistrationTime(String lastRegistrationTime) {
    this.lastRegistrationTime = lastRegistrationTime;
    return this;
  }

  /**
   * Last registration timestamp.
   * @return lastRegistrationTime
   */
  @javax.annotation.Nullable
  public String getLastRegistrationTime() {
    return lastRegistrationTime;
  }

  public void setLastRegistrationTime(String lastRegistrationTime) {
    this.lastRegistrationTime = lastRegistrationTime;
  }


  public Lines hostIP(String hostIP) {
    this.hostIP = hostIP;
    return this;
  }

  /**
   * Registration host IP address for the line port.
   * @return hostIP
   */
  @javax.annotation.Nullable
  public String getHostIP() {
    return hostIP;
  }

  public void setHostIP(String hostIP) {
    this.hostIP = hostIP;
  }


  public Lines remoteIP(String remoteIP) {
    this.remoteIP = remoteIP;
    return this;
  }

  /**
   * Registration remote IP address for the line port.
   * @return remoteIP
   */
  @javax.annotation.Nullable
  public String getRemoteIP() {
    return remoteIP;
  }

  public void setRemoteIP(String remoteIP) {
    this.remoteIP = remoteIP;
  }


  public Lines location(Location location) {
    this.location = location;
    return this;
  }

  /**
   * Get location
   * @return location
   */
  @javax.annotation.Nonnull
  public Location getLocation() {
    return location;
  }

  public void setLocation(Location location) {
    this.location = location;
  }


  public Lines memberType(MemberType memberType) {
    this.memberType = memberType;
    return this;
  }

  /**
   * Indicates member type.
   * @return memberType
   */
  @javax.annotation.Nonnull
  public MemberType getMemberType() {
    return memberType;
  }

  public void setMemberType(MemberType memberType) {
    this.memberType = memberType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Lines lines = (Lines) o;
    return Objects.equals(this.memberId, lines.memberId) &&
        Objects.equals(this.firstName, lines.firstName) &&
        Objects.equals(this.lastName, lines.lastName) &&
        Objects.equals(this.external, lines.external) &&
        Objects.equals(this.extension, lines.extension) &&
        Objects.equals(this.lastRegistrationTime, lines.lastRegistrationTime) &&
        Objects.equals(this.hostIP, lines.hostIP) &&
        Objects.equals(this.remoteIP, lines.remoteIP) &&
        Objects.equals(this.location, lines.location) &&
        Objects.equals(this.memberType, lines.memberType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(memberId, firstName, lastName, external, extension, lastRegistrationTime, hostIP, remoteIP, location, memberType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Lines {\n");
    sb.append("    memberId: ").append(toIndentedString(memberId)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    external: ").append(toIndentedString(external)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    lastRegistrationTime: ").append(toIndentedString(lastRegistrationTime)).append("\n");
    sb.append("    hostIP: ").append(toIndentedString(hostIP)).append("\n");
    sb.append("    remoteIP: ").append(toIndentedString(remoteIP)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    memberType: ").append(toIndentedString(memberType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("memberId");
    openapiFields.add("firstName");
    openapiFields.add("lastName");
    openapiFields.add("external");
    openapiFields.add("extension");
    openapiFields.add("lastRegistrationTime");
    openapiFields.add("hostIP");
    openapiFields.add("remoteIP");
    openapiFields.add("location");
    openapiFields.add("memberType");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("memberId");
    openapiRequiredFields.add("firstName");
    openapiRequiredFields.add("lastName");
    openapiRequiredFields.add("location");
    openapiRequiredFields.add("memberType");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Lines
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Lines.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Lines is not found in the empty JSON string", Lines.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Lines.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Lines` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Lines.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("memberId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `memberId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("memberId").toString()));
      }
      if (!jsonObj.get("firstName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `firstName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("firstName").toString()));
      }
      if (!jsonObj.get("lastName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lastName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastName").toString()));
      }
      if ((jsonObj.get("external") != null && !jsonObj.get("external").isJsonNull()) && !jsonObj.get("external").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `external` to be a primitive type in the JSON string but got `%s`", jsonObj.get("external").toString()));
      }
      if ((jsonObj.get("extension") != null && !jsonObj.get("extension").isJsonNull()) && !jsonObj.get("extension").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `extension` to be a primitive type in the JSON string but got `%s`", jsonObj.get("extension").toString()));
      }
      if ((jsonObj.get("lastRegistrationTime") != null && !jsonObj.get("lastRegistrationTime").isJsonNull()) && !jsonObj.get("lastRegistrationTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lastRegistrationTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastRegistrationTime").toString()));
      }
      if ((jsonObj.get("hostIP") != null && !jsonObj.get("hostIP").isJsonNull()) && !jsonObj.get("hostIP").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hostIP` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hostIP").toString()));
      }
      if ((jsonObj.get("remoteIP") != null && !jsonObj.get("remoteIP").isJsonNull()) && !jsonObj.get("remoteIP").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `remoteIP` to be a primitive type in the JSON string but got `%s`", jsonObj.get("remoteIP").toString()));
      }
      // validate the required field `location`
      Location.validateJsonElement(jsonObj.get("location"));
      // validate the required field `memberType`
      MemberType.validateJsonElement(jsonObj.get("memberType"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Lines.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Lines' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Lines> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Lines.class));

       return (TypeAdapter<T>) new TypeAdapter<Lines>() {
           @Override
           public void write(JsonWriter out, Lines value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Lines read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Lines given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Lines
   * @throws IOException if the JSON string is invalid with respect to Lines
   */
  public static Lines fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Lines.class);
  }

  /**
   * Convert an instance of Lines to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

