// Copyright 2025 Cisco Systems Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

/*
 * All Webex calling API
 * Webex calling API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.CallBackSelectedPatch;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PutECBNObject
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-13T15:45:43.258095Z[Europe/Dublin]", comments = "Generator version: 7.9.0")
public class PutECBNObject {
  public static final String SERIALIZED_NAME_SELECTED = "selected";
  @SerializedName(SERIALIZED_NAME_SELECTED)
  private CallBackSelectedPatch selected;

  public static final String SERIALIZED_NAME_LOCATION_MEMBER_ID = "locationMemberId";
  @SerializedName(SERIALIZED_NAME_LOCATION_MEMBER_ID)
  private String locationMemberId;

  public PutECBNObject() {
  }

  public PutECBNObject selected(CallBackSelectedPatch selected) {
    this.selected = selected;
    return this;
  }

  /**
   * Get selected
   * @return selected
   */
  @javax.annotation.Nonnull
  public CallBackSelectedPatch getSelected() {
    return selected;
  }

  public void setSelected(CallBackSelectedPatch selected) {
    this.selected = selected;
  }


  public PutECBNObject locationMemberId(String locationMemberId) {
    this.locationMemberId = locationMemberId;
    return this;
  }

  /**
   * Member ID of person/workspace/virtual line within the location. Required when &#x60;selected&#x60; is &#x60;LOCATION_MEMBER_NUMBER&#x60;.
   * @return locationMemberId
   */
  @javax.annotation.Nullable
  public String getLocationMemberId() {
    return locationMemberId;
  }

  public void setLocationMemberId(String locationMemberId) {
    this.locationMemberId = locationMemberId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PutECBNObject putECBNObject = (PutECBNObject) o;
    return Objects.equals(this.selected, putECBNObject.selected) &&
        Objects.equals(this.locationMemberId, putECBNObject.locationMemberId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(selected, locationMemberId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PutECBNObject {\n");
    sb.append("    selected: ").append(toIndentedString(selected)).append("\n");
    sb.append("    locationMemberId: ").append(toIndentedString(locationMemberId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("selected");
    openapiFields.add("locationMemberId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("selected");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PutECBNObject
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PutECBNObject.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PutECBNObject is not found in the empty JSON string", PutECBNObject.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PutECBNObject.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PutECBNObject` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PutECBNObject.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `selected`
      CallBackSelectedPatch.validateJsonElement(jsonObj.get("selected"));
      if ((jsonObj.get("locationMemberId") != null && !jsonObj.get("locationMemberId").isJsonNull()) && !jsonObj.get("locationMemberId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `locationMemberId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("locationMemberId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PutECBNObject.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PutECBNObject' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PutECBNObject> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PutECBNObject.class));

       return (TypeAdapter<T>) new TypeAdapter<PutECBNObject>() {
           @Override
           public void write(JsonWriter out, PutECBNObject value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PutECBNObject read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PutECBNObject given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PutECBNObject
   * @throws IOException if the JSON string is invalid with respect to PutECBNObject
   */
  public static PutECBNObject fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PutECBNObject.class);
  }

  /**
   * Convert an instance of PutECBNObject to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

