// Copyright 2025 Cisco Systems Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

/*
 * All Webex calling API
 * Webex calling API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.RetrieveSequentialRingSettingsForAWorkspace200ResponseCriteriaInner;
import org.openapitools.client.model.RetrieveSequentialRingSettingsForAWorkspace200ResponsePhoneNumbersInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * RetrieveSequentialRingSettingsForAWorkspace200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-13T15:45:43.258095Z[Europe/Dublin]", comments = "Generator version: 7.9.0")
public class RetrieveSequentialRingSettingsForAWorkspace200Response {
  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  private Boolean enabled;

  public static final String SERIALIZED_NAME_RING_BASE_LOCATION_FIRST_ENABLED = "ringBaseLocationFirstEnabled";
  @SerializedName(SERIALIZED_NAME_RING_BASE_LOCATION_FIRST_ENABLED)
  private Boolean ringBaseLocationFirstEnabled;

  public static final String SERIALIZED_NAME_BASE_LOCATION_NUMBER_OF_RINGS = "baseLocationNumberOfRings";
  @SerializedName(SERIALIZED_NAME_BASE_LOCATION_NUMBER_OF_RINGS)
  private String baseLocationNumberOfRings;

  public static final String SERIALIZED_NAME_CONTINUE_IF_BASE_LOCATION_IS_BUSY_ENABLED = "continueIfBaseLocationIsBusyEnabled";
  @SerializedName(SERIALIZED_NAME_CONTINUE_IF_BASE_LOCATION_IS_BUSY_ENABLED)
  private Boolean continueIfBaseLocationIsBusyEnabled;

  public static final String SERIALIZED_NAME_CALLS_TO_VOICEMAIL_ENABLED = "callsToVoicemailEnabled";
  @SerializedName(SERIALIZED_NAME_CALLS_TO_VOICEMAIL_ENABLED)
  private Boolean callsToVoicemailEnabled;

  public static final String SERIALIZED_NAME_PHONE_NUMBERS = "phoneNumbers";
  @SerializedName(SERIALIZED_NAME_PHONE_NUMBERS)
  private List<RetrieveSequentialRingSettingsForAWorkspace200ResponsePhoneNumbersInner> phoneNumbers = new ArrayList<>();

  public static final String SERIALIZED_NAME_CRITERIA = "criteria";
  @SerializedName(SERIALIZED_NAME_CRITERIA)
  private List<RetrieveSequentialRingSettingsForAWorkspace200ResponseCriteriaInner> criteria = new ArrayList<>();

  public RetrieveSequentialRingSettingsForAWorkspace200Response() {
  }

  public RetrieveSequentialRingSettingsForAWorkspace200Response enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * When set to &#x60;true&#x60; sequential ring is enabled.
   * @return enabled
   */
  @javax.annotation.Nonnull
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  public RetrieveSequentialRingSettingsForAWorkspace200Response ringBaseLocationFirstEnabled(Boolean ringBaseLocationFirstEnabled) {
    this.ringBaseLocationFirstEnabled = ringBaseLocationFirstEnabled;
    return this;
  }

  /**
   * When set to &#x60;true&#x60;, the webex calling primary line will ring first.
   * @return ringBaseLocationFirstEnabled
   */
  @javax.annotation.Nonnull
  public Boolean getRingBaseLocationFirstEnabled() {
    return ringBaseLocationFirstEnabled;
  }

  public void setRingBaseLocationFirstEnabled(Boolean ringBaseLocationFirstEnabled) {
    this.ringBaseLocationFirstEnabled = ringBaseLocationFirstEnabled;
  }


  public RetrieveSequentialRingSettingsForAWorkspace200Response baseLocationNumberOfRings(String baseLocationNumberOfRings) {
    this.baseLocationNumberOfRings = baseLocationNumberOfRings;
    return this;
  }

  /**
   * The number of times the primary line will ring.
   * @return baseLocationNumberOfRings
   */
  @javax.annotation.Nonnull
  public String getBaseLocationNumberOfRings() {
    return baseLocationNumberOfRings;
  }

  public void setBaseLocationNumberOfRings(String baseLocationNumberOfRings) {
    this.baseLocationNumberOfRings = baseLocationNumberOfRings;
  }


  public RetrieveSequentialRingSettingsForAWorkspace200Response continueIfBaseLocationIsBusyEnabled(Boolean continueIfBaseLocationIsBusyEnabled) {
    this.continueIfBaseLocationIsBusyEnabled = continueIfBaseLocationIsBusyEnabled;
    return this;
  }

  /**
   * When set to &#x60;true&#x60; and the primary line is busy, the system redirects calls to the numbers configured for sequential ringing.
   * @return continueIfBaseLocationIsBusyEnabled
   */
  @javax.annotation.Nonnull
  public Boolean getContinueIfBaseLocationIsBusyEnabled() {
    return continueIfBaseLocationIsBusyEnabled;
  }

  public void setContinueIfBaseLocationIsBusyEnabled(Boolean continueIfBaseLocationIsBusyEnabled) {
    this.continueIfBaseLocationIsBusyEnabled = continueIfBaseLocationIsBusyEnabled;
  }


  public RetrieveSequentialRingSettingsForAWorkspace200Response callsToVoicemailEnabled(Boolean callsToVoicemailEnabled) {
    this.callsToVoicemailEnabled = callsToVoicemailEnabled;
    return this;
  }

  /**
   * When set to &#x60;true&#x60; calls are directed to voicemail.
   * @return callsToVoicemailEnabled
   */
  @javax.annotation.Nonnull
  public Boolean getCallsToVoicemailEnabled() {
    return callsToVoicemailEnabled;
  }

  public void setCallsToVoicemailEnabled(Boolean callsToVoicemailEnabled) {
    this.callsToVoicemailEnabled = callsToVoicemailEnabled;
  }


  public RetrieveSequentialRingSettingsForAWorkspace200Response phoneNumbers(List<RetrieveSequentialRingSettingsForAWorkspace200ResponsePhoneNumbersInner> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
    return this;
  }

  public RetrieveSequentialRingSettingsForAWorkspace200Response addPhoneNumbersItem(RetrieveSequentialRingSettingsForAWorkspace200ResponsePhoneNumbersInner phoneNumbersItem) {
    if (this.phoneNumbers == null) {
      this.phoneNumbers = new ArrayList<>();
    }
    this.phoneNumbers.add(phoneNumbersItem);
    return this;
  }

  /**
   * A list of up to five phone numbers to which calls will be directed.
   * @return phoneNumbers
   */
  @javax.annotation.Nonnull
  public List<RetrieveSequentialRingSettingsForAWorkspace200ResponsePhoneNumbersInner> getPhoneNumbers() {
    return phoneNumbers;
  }

  public void setPhoneNumbers(List<RetrieveSequentialRingSettingsForAWorkspace200ResponsePhoneNumbersInner> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
  }


  public RetrieveSequentialRingSettingsForAWorkspace200Response criteria(List<RetrieveSequentialRingSettingsForAWorkspace200ResponseCriteriaInner> criteria) {
    this.criteria = criteria;
    return this;
  }

  public RetrieveSequentialRingSettingsForAWorkspace200Response addCriteriaItem(RetrieveSequentialRingSettingsForAWorkspace200ResponseCriteriaInner criteriaItem) {
    if (this.criteria == null) {
      this.criteria = new ArrayList<>();
    }
    this.criteria.add(criteriaItem);
    return this;
  }

  /**
   * A list of criteria specifying conditions when sequential ringing is in effect.
   * @return criteria
   */
  @javax.annotation.Nonnull
  public List<RetrieveSequentialRingSettingsForAWorkspace200ResponseCriteriaInner> getCriteria() {
    return criteria;
  }

  public void setCriteria(List<RetrieveSequentialRingSettingsForAWorkspace200ResponseCriteriaInner> criteria) {
    this.criteria = criteria;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetrieveSequentialRingSettingsForAWorkspace200Response retrieveSequentialRingSettingsForAWorkspace200Response = (RetrieveSequentialRingSettingsForAWorkspace200Response) o;
    return Objects.equals(this.enabled, retrieveSequentialRingSettingsForAWorkspace200Response.enabled) &&
        Objects.equals(this.ringBaseLocationFirstEnabled, retrieveSequentialRingSettingsForAWorkspace200Response.ringBaseLocationFirstEnabled) &&
        Objects.equals(this.baseLocationNumberOfRings, retrieveSequentialRingSettingsForAWorkspace200Response.baseLocationNumberOfRings) &&
        Objects.equals(this.continueIfBaseLocationIsBusyEnabled, retrieveSequentialRingSettingsForAWorkspace200Response.continueIfBaseLocationIsBusyEnabled) &&
        Objects.equals(this.callsToVoicemailEnabled, retrieveSequentialRingSettingsForAWorkspace200Response.callsToVoicemailEnabled) &&
        Objects.equals(this.phoneNumbers, retrieveSequentialRingSettingsForAWorkspace200Response.phoneNumbers) &&
        Objects.equals(this.criteria, retrieveSequentialRingSettingsForAWorkspace200Response.criteria);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, ringBaseLocationFirstEnabled, baseLocationNumberOfRings, continueIfBaseLocationIsBusyEnabled, callsToVoicemailEnabled, phoneNumbers, criteria);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetrieveSequentialRingSettingsForAWorkspace200Response {\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    ringBaseLocationFirstEnabled: ").append(toIndentedString(ringBaseLocationFirstEnabled)).append("\n");
    sb.append("    baseLocationNumberOfRings: ").append(toIndentedString(baseLocationNumberOfRings)).append("\n");
    sb.append("    continueIfBaseLocationIsBusyEnabled: ").append(toIndentedString(continueIfBaseLocationIsBusyEnabled)).append("\n");
    sb.append("    callsToVoicemailEnabled: ").append(toIndentedString(callsToVoicemailEnabled)).append("\n");
    sb.append("    phoneNumbers: ").append(toIndentedString(phoneNumbers)).append("\n");
    sb.append("    criteria: ").append(toIndentedString(criteria)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("enabled");
    openapiFields.add("ringBaseLocationFirstEnabled");
    openapiFields.add("baseLocationNumberOfRings");
    openapiFields.add("continueIfBaseLocationIsBusyEnabled");
    openapiFields.add("callsToVoicemailEnabled");
    openapiFields.add("phoneNumbers");
    openapiFields.add("criteria");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("enabled");
    openapiRequiredFields.add("ringBaseLocationFirstEnabled");
    openapiRequiredFields.add("baseLocationNumberOfRings");
    openapiRequiredFields.add("continueIfBaseLocationIsBusyEnabled");
    openapiRequiredFields.add("callsToVoicemailEnabled");
    openapiRequiredFields.add("phoneNumbers");
    openapiRequiredFields.add("criteria");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RetrieveSequentialRingSettingsForAWorkspace200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RetrieveSequentialRingSettingsForAWorkspace200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RetrieveSequentialRingSettingsForAWorkspace200Response is not found in the empty JSON string", RetrieveSequentialRingSettingsForAWorkspace200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RetrieveSequentialRingSettingsForAWorkspace200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RetrieveSequentialRingSettingsForAWorkspace200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RetrieveSequentialRingSettingsForAWorkspace200Response.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("baseLocationNumberOfRings").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `baseLocationNumberOfRings` to be a primitive type in the JSON string but got `%s`", jsonObj.get("baseLocationNumberOfRings").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("phoneNumbers").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `phoneNumbers` to be an array in the JSON string but got `%s`", jsonObj.get("phoneNumbers").toString()));
      }

      JsonArray jsonArrayphoneNumbers = jsonObj.getAsJsonArray("phoneNumbers");
      // validate the required field `phoneNumbers` (array)
      for (int i = 0; i < jsonArrayphoneNumbers.size(); i++) {
        RetrieveSequentialRingSettingsForAWorkspace200ResponsePhoneNumbersInner.validateJsonElement(jsonArrayphoneNumbers.get(i));
      };
      // ensure the json data is an array
      if (!jsonObj.get("criteria").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `criteria` to be an array in the JSON string but got `%s`", jsonObj.get("criteria").toString()));
      }

      JsonArray jsonArraycriteria = jsonObj.getAsJsonArray("criteria");
      // validate the required field `criteria` (array)
      for (int i = 0; i < jsonArraycriteria.size(); i++) {
        RetrieveSequentialRingSettingsForAWorkspace200ResponseCriteriaInner.validateJsonElement(jsonArraycriteria.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RetrieveSequentialRingSettingsForAWorkspace200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RetrieveSequentialRingSettingsForAWorkspace200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RetrieveSequentialRingSettingsForAWorkspace200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RetrieveSequentialRingSettingsForAWorkspace200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<RetrieveSequentialRingSettingsForAWorkspace200Response>() {
           @Override
           public void write(JsonWriter out, RetrieveSequentialRingSettingsForAWorkspace200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RetrieveSequentialRingSettingsForAWorkspace200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RetrieveSequentialRingSettingsForAWorkspace200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RetrieveSequentialRingSettingsForAWorkspace200Response
   * @throws IOException if the JSON string is invalid with respect to RetrieveSequentialRingSettingsForAWorkspace200Response
   */
  public static RetrieveSequentialRingSettingsForAWorkspace200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RetrieveSequentialRingSettingsForAWorkspace200Response.class);
  }

  /**
   * Convert an instance of RetrieveSequentialRingSettingsForAWorkspace200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

