// Copyright 2025 Cisco Systems Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

/*
 * All Webex calling API
 * Webex calling API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * SimultaneousRingNumberGet
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-13T15:45:43.258095Z[Europe/Dublin]", comments = "Generator version: 7.9.0")
public class SimultaneousRingNumberGet {
  public static final String SERIALIZED_NAME_PHONE_NUMBER = "phoneNumber";
  @SerializedName(SERIALIZED_NAME_PHONE_NUMBER)
  private String phoneNumber;

  public static final String SERIALIZED_NAME_ANSWER_CONFIRMATION_ENABLED = "answerConfirmationEnabled";
  @SerializedName(SERIALIZED_NAME_ANSWER_CONFIRMATION_ENABLED)
  private Boolean answerConfirmationEnabled;

  public static final String SERIALIZED_NAME_ANSWER_CONFIRMATION_REQUIRED_ENABLED = "answerConfirmationRequiredEnabled";
  @SerializedName(SERIALIZED_NAME_ANSWER_CONFIRMATION_REQUIRED_ENABLED)
  private Boolean answerConfirmationRequiredEnabled;

  public SimultaneousRingNumberGet() {
  }

  public SimultaneousRingNumberGet phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

  /**
   * Phone number set as the sequential number.
   * @return phoneNumber
   */
  @javax.annotation.Nonnull
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public SimultaneousRingNumberGet answerConfirmationEnabled(Boolean answerConfirmationEnabled) {
    this.answerConfirmationEnabled = answerConfirmationEnabled;
    return this;
  }

  /**
   * When set to &#x60;true&#x60; the called party is required to press 1 on the keypad to receive the call.
   * @return answerConfirmationEnabled
   */
  @javax.annotation.Nonnull
  public Boolean getAnswerConfirmationEnabled() {
    return answerConfirmationEnabled;
  }

  public void setAnswerConfirmationEnabled(Boolean answerConfirmationEnabled) {
    this.answerConfirmationEnabled = answerConfirmationEnabled;
  }


  public SimultaneousRingNumberGet answerConfirmationRequiredEnabled(Boolean answerConfirmationRequiredEnabled) {
    this.answerConfirmationRequiredEnabled = answerConfirmationRequiredEnabled;
    return this;
  }

  /**
   * When set to &#x60;true&#x60; the called party is required to press 1 on the keypad to receive the call.
   * @return answerConfirmationRequiredEnabled
   */
  @javax.annotation.Nonnull
  public Boolean getAnswerConfirmationRequiredEnabled() {
    return answerConfirmationRequiredEnabled;
  }

  public void setAnswerConfirmationRequiredEnabled(Boolean answerConfirmationRequiredEnabled) {
    this.answerConfirmationRequiredEnabled = answerConfirmationRequiredEnabled;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimultaneousRingNumberGet simultaneousRingNumberGet = (SimultaneousRingNumberGet) o;
    return Objects.equals(this.phoneNumber, simultaneousRingNumberGet.phoneNumber) &&
        Objects.equals(this.answerConfirmationEnabled, simultaneousRingNumberGet.answerConfirmationEnabled) &&
        Objects.equals(this.answerConfirmationRequiredEnabled, simultaneousRingNumberGet.answerConfirmationRequiredEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phoneNumber, answerConfirmationEnabled, answerConfirmationRequiredEnabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimultaneousRingNumberGet {\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    answerConfirmationEnabled: ").append(toIndentedString(answerConfirmationEnabled)).append("\n");
    sb.append("    answerConfirmationRequiredEnabled: ").append(toIndentedString(answerConfirmationRequiredEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("phoneNumber");
    openapiFields.add("answerConfirmationEnabled");
    openapiFields.add("answerConfirmationRequiredEnabled");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("phoneNumber");
    openapiRequiredFields.add("answerConfirmationEnabled");
    openapiRequiredFields.add("answerConfirmationRequiredEnabled");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SimultaneousRingNumberGet
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SimultaneousRingNumberGet.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SimultaneousRingNumberGet is not found in the empty JSON string", SimultaneousRingNumberGet.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SimultaneousRingNumberGet.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SimultaneousRingNumberGet` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SimultaneousRingNumberGet.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("phoneNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `phoneNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("phoneNumber").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SimultaneousRingNumberGet.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SimultaneousRingNumberGet' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SimultaneousRingNumberGet> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SimultaneousRingNumberGet.class));

       return (TypeAdapter<T>) new TypeAdapter<SimultaneousRingNumberGet>() {
           @Override
           public void write(JsonWriter out, SimultaneousRingNumberGet value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SimultaneousRingNumberGet read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SimultaneousRingNumberGet given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SimultaneousRingNumberGet
   * @throws IOException if the JSON string is invalid with respect to SimultaneousRingNumberGet
   */
  public static SimultaneousRingNumberGet fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SimultaneousRingNumberGet.class);
  }

  /**
   * Convert an instance of SimultaneousRingNumberGet to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

